-- crear_tablas.sql
-- Estructura completa para el formulario reducido de diagnóstico comercial de Pixels Studio.
-- Ejecutar desde phpMyAdmin o mediante instalar_base_datos.php.

CREATE TABLE IF NOT EXISTS `accounts` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(160) NOT NULL,
  `slug` VARCHAR(80) NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'active',
  `plan` VARCHAR(60) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_slug` (`slug`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `accounts` (`id`, `name`, `slug`, `status`)
VALUES (1, 'Pixels Studio', 'pixels-studio', 'active')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `status`=VALUES(`status`);

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `account_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `username` VARCHAR(60) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` VARCHAR(30) NOT NULL DEFAULT 'super_admin',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_account_id` (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `leads` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `account_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `fullname` VARCHAR(120) NOT NULL,
  `phone` VARCHAR(64) NULL,
  `email` VARCHAR(150) NULL,
  `brand_instagram` VARCHAR(120) NULL,
  `business_type` VARCHAR(80) NULL,
  `business_type_other` VARCHAR(120) NULL,
  `services_needed` TEXT NULL,
  `main_objective` VARCHAR(120) NULL,
  `message` TEXT NULL,
  `source_platform` VARCHAR(80) NULL,
  `utm_source` VARCHAR(80) NULL,
  `utm_medium` VARCHAR(80) NULL,
  `utm_campaign` VARCHAR(120) NULL,
  `campaign_id` VARCHAR(120) NULL,
  `campaign_name` VARCHAR(180) NULL,
  `campaign_ref_id` INT UNSIGNED NULL,
  `utm_content` VARCHAR(160) NULL,
  `utm_term` VARCHAR(160) NULL,
  `adset_id` VARCHAR(120) NULL,
  `adset_name` VARCHAR(180) NULL,
  `adset_ref_id` INT UNSIGNED NULL,
  `ad_name` VARCHAR(180) NULL,
  `ad_id` VARCHAR(120) NULL,
  `ad_ref_id` INT UNSIGNED NULL,
  `ad_referral_source` VARCHAR(80) NULL,
  `ad_referral_type` VARCHAR(80) NULL,
  `ad_referral_payload` TEXT NULL,
  `ad_enrichment_error` VARCHAR(255) NULL,
  `gclid` VARCHAR(180) NULL,
  `fbclid` VARCHAR(180) NULL,
  `landing_url` TEXT NULL,
  `referrer` TEXT NULL,
  `sales_status` VARCHAR(50) NOT NULL DEFAULT 'nuevo_lead',
  `notes` TEXT NULL,
  `reminder_at` DATETIME NULL,
  `reminder_note` VARCHAR(255) NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `ip` VARCHAR(64) NULL,
  `user_agent` VARCHAR(255) NULL,
  `whatsapp_sent` TINYINT(1) NOT NULL DEFAULT 0,
  `whatsapp_status` VARCHAR(32) NULL,
  `external_source` VARCHAR(40) NULL,
  `external_contact_id` VARCHAR(120) NULL,
  `external_thread_id` VARCHAR(120) NULL,
  `last_external_message_id` TEXT NULL,
  `first_message_at` DATETIME NULL,
  `last_message_at` DATETIME NULL,
  `last_inbound_message` TEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_phone` (`phone`),
  UNIQUE KEY `uniq_external_contact` (`account_id`, `external_source`, `external_contact_id`),
  KEY `idx_account_id` (`account_id`),
  KEY `idx_brand_instagram` (`brand_instagram`),
  KEY `idx_business_type` (`business_type`),
  KEY `idx_main_objective` (`main_objective`),
  KEY `idx_source_platform` (`source_platform`),
  KEY `idx_utm_campaign` (`utm_campaign`),
  KEY `idx_campaign_name` (`campaign_name`),
  KEY `idx_campaign_ref_id` (`campaign_ref_id`),
  KEY `idx_adset_name` (`adset_name`),
  KEY `idx_adset_ref_id` (`adset_ref_id`),
  KEY `idx_utm_content` (`utm_content`),
  KEY `idx_ad_name` (`ad_name`),
  KEY `idx_ad_id` (`ad_id`),
  KEY `idx_ad_ref_id` (`ad_ref_id`),
  KEY `idx_sales_status` (`sales_status`),
  KEY `idx_reminder_at` (`reminder_at`),
  KEY `idx_last_message_at` (`last_message_at`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ad_campaigns` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `account_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `provider` VARCHAR(40) NOT NULL DEFAULT 'meta',
  `campaign_key` VARCHAR(180) NOT NULL,
  `external_campaign_id` VARCHAR(120) NULL,
  `campaign_name` VARCHAR(180) NOT NULL,
  `first_seen_at` DATETIME NULL,
  `last_seen_at` DATETIME NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_campaign` (`account_id`, `provider`, `campaign_key`),
  KEY `idx_account_id` (`account_id`),
  KEY `idx_campaign_name` (`campaign_name`),
  KEY `idx_last_seen_at` (`last_seen_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ad_sets` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `account_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `campaign_ref_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `provider` VARCHAR(40) NOT NULL DEFAULT 'meta',
  `adset_key` VARCHAR(180) NOT NULL,
  `external_adset_id` VARCHAR(120) NULL,
  `adset_name` VARCHAR(180) NOT NULL,
  `first_seen_at` DATETIME NULL,
  `last_seen_at` DATETIME NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_adset` (`account_id`, `provider`, `campaign_ref_id`, `adset_key`),
  KEY `idx_account_id` (`account_id`),
  KEY `idx_campaign_ref_id` (`campaign_ref_id`),
  KEY `idx_adset_name` (`adset_name`),
  KEY `idx_last_seen_at` (`last_seen_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ads` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `account_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `campaign_ref_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `adset_ref_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `provider` VARCHAR(40) NOT NULL DEFAULT 'meta',
  `ad_key` VARCHAR(180) NOT NULL,
  `external_ad_id` VARCHAR(120) NULL,
  `ad_name` VARCHAR(180) NOT NULL,
  `first_seen_at` DATETIME NULL,
  `last_seen_at` DATETIME NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_ad` (`account_id`, `provider`, `ad_key`),
  KEY `idx_account_id` (`account_id`),
  KEY `idx_campaign_ref_id` (`campaign_ref_id`),
  KEY `idx_adset_ref_id` (`adset_ref_id`),
  KEY `idx_ad_name` (`ad_name`),
  KEY `idx_last_seen_at` (`last_seen_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `instagram_channels` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `account_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `connection_type` VARCHAR(40) NOT NULL DEFAULT 'facebook',
  `page_id` VARCHAR(120) NOT NULL,
  `page_name` VARCHAR(180) NULL,
  `instagram_user_id` VARCHAR(120) NOT NULL,
  `instagram_username` VARCHAR(180) NULL,
  `page_access_token` TEXT NULL,
  `token_expires_at` DATETIME NULL,
  `scopes` TEXT NULL,
  `connected_by` INT UNSIGNED NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `last_event_at` DATETIME NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_page_id` (`page_id`),
  UNIQUE KEY `uniq_instagram_user_id` (`instagram_user_id`),
  KEY `idx_account_id` (`account_id`),
  KEY `idx_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `conversation_contacts` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `account_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `external_source` VARCHAR(40) NOT NULL,
  `external_contact_id` VARCHAR(160) NOT NULL,
  `display_name` VARCHAR(180) NULL,
  `username` VARCHAR(180) NULL,
  `profile_url` VARCHAR(255) NULL,
  `last_seen_at` DATETIME NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_external_contact` (`account_id`, `external_source`, `external_contact_id`),
  KEY `idx_account_id` (`account_id`),
  KEY `idx_username` (`username`),
  KEY `idx_last_seen_at` (`last_seen_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `conversations` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `account_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `public_id` INT UNSIGNED NULL,
  `channel_id` INT UNSIGNED NULL,
  `contact_id` INT UNSIGNED NOT NULL,
  `lead_id` INT UNSIGNED NULL,
  `external_source` VARCHAR(40) NOT NULL,
  `external_thread_id` VARCHAR(180) NOT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'abierta',
  `assigned_to` INT UNSIGNED NULL,
  `last_message_preview` TEXT NULL,
  `last_message_at` DATETIME NULL,
  `unread_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_external_thread` (`account_id`, `external_source`, `external_thread_id`),
  UNIQUE KEY `uniq_account_public_id` (`account_id`, `public_id`),
  KEY `idx_account_id` (`account_id`),
  KEY `idx_channel_id` (`channel_id`),
  KEY `idx_contact_id` (`contact_id`),
  KEY `idx_lead_id` (`lead_id`),
  KEY `idx_status` (`status`),
  KEY `idx_assigned_to` (`assigned_to`),
  KEY `idx_last_message_at` (`last_message_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `conversation_messages` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `account_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `conversation_id` INT UNSIGNED NOT NULL,
  `external_message_id` TEXT NULL,
  `external_message_hash` CHAR(64) NULL,
  `direction` VARCHAR(20) NOT NULL,
  `sender_external_id` VARCHAR(180) NULL,
  `message_type` VARCHAR(40) NOT NULL DEFAULT 'text',
  `message_text` TEXT NULL,
  `payload_json` MEDIUMTEXT NULL,
  `sent_by` INT UNSIGNED NULL,
  `sent_at` DATETIME NOT NULL,
  `delivery_status` VARCHAR(40) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_conversation_message_hash` (`conversation_id`, `external_message_hash`),
  KEY `idx_account_id` (`account_id`),
  KEY `idx_conversation_id` (`conversation_id`),
  KEY `idx_direction` (`direction`),
  KEY `idx_sent_at` (`sent_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `conversation_attachments` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `account_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `conversation_id` INT UNSIGNED NOT NULL,
  `message_id` INT UNSIGNED NULL,
  `direction` VARCHAR(20) NOT NULL,
  `media_type` VARCHAR(40) NOT NULL DEFAULT 'image',
  `mime_type` VARCHAR(120) NULL,
  `file_size` INT UNSIGNED NULL,
  `storage_disk` VARCHAR(40) NOT NULL DEFAULT 'r2',
  `storage_key` VARCHAR(500) NOT NULL,
  `original_url` TEXT NULL,
  `filename` VARCHAR(180) NULL,
  `external_attachment_id` VARCHAR(180) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_storage_key` (`storage_key`),
  KEY `idx_account_id` (`account_id`),
  KEY `idx_conversation_id` (`conversation_id`),
  KEY `idx_message_id` (`message_id`),
  KEY `idx_media_type` (`media_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `webhook_event_logs` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `account_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `source` VARCHAR(40) NOT NULL DEFAULT 'instagram',
  `event_type` VARCHAR(60) NULL,
  `status` VARCHAR(40) NOT NULL,
  `recipient_id` VARCHAR(180) NULL,
  `sender_id` VARCHAR(180) NULL,
  `channel_id` INT UNSIGNED NULL,
  `channel_username` VARCHAR(180) NULL,
  `external_message_id` TEXT NULL,
  `lead_id` INT UNSIGNED NULL,
  `conversation_id` INT UNSIGNED NULL,
  `message_preview` VARCHAR(255) NULL,
  `error_message` VARCHAR(255) NULL,
  `payload_json` MEDIUMTEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_source_created_at` (`source`, `created_at`),
  KEY `idx_account_id` (`account_id`),
  KEY `idx_status` (`status`),
  KEY `idx_recipient_id` (`recipient_id`),
  KEY `idx_sender_id` (`sender_id`),
  KEY `idx_channel_id` (`channel_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_knowledge_items` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `account_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `title` VARCHAR(180) NOT NULL,
  `response_text` TEXT NOT NULL,
  `raw_response_text` TEXT NULL,
  `response_hash` CHAR(64) NOT NULL,
  `context_hash` CHAR(64) NULL,
  `category` VARCHAR(60) NOT NULL DEFAULT 'ai_suggestion',
  `source` VARCHAR(60) NOT NULL DEFAULT 'ai_suggestion',
  `source_conversation_id` INT UNSIGNED NULL,
  `source_message_id` INT UNSIGNED NULL,
  `analysis_json` LONGTEXT NULL,
  `confidence` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `is_approved` TINYINT(1) NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 0,
  `usage_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `last_used_at` DATETIME NULL,
  `created_by` INT UNSIGNED NULL,
  `approved_by` INT UNSIGNED NULL,
  `approved_at` DATETIME NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_account_response_hash` (`account_id`, `response_hash`),
  UNIQUE KEY `uniq_account_context_hash` (`account_id`, `context_hash`),
  KEY `idx_account_approved_active` (`account_id`, `is_approved`, `is_active`),
  KEY `idx_source_conversation` (`source_conversation_id`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
